# Generated by Django 2.2.4 on 2020-04-03 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_slides'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slides',
            options={'default_related_name': 'slides'},
        ),
    ]
