# Generated by Django 2.2.4 on 2020-04-12 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20200403_1443'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadDocuments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='Documents/')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.AlterModelOptions(
            name='documents',
            options={'default_related_name': 'documents'},
        ),
        migrations.AlterModelOptions(
            name='exams',
            options={'default_related_name': 'exams'},
        ),
    ]
