# Generated by Django 2.2.4 on 2020-04-12 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20200412_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploaddocuments',
            name='name',
            field=models.CharField(default='', max_length=200, unique=True),
        ),
    ]
