# Generated by Django 2.2.4 on 2020-04-12 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_uploaddocuments_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadExams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam', models.FileField(upload_to='Examination/')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(default='', max_length=200, unique=True)),
                ('teacher', models.CharField(max_length=200)),
                ('exam_id', models.CharField(max_length=15)),
            ],
        ),
    ]
