# Generated by Django 2.2.4 on 2020-04-13 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_uploadexams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploaddocuments',
            name='document',
            field=models.FileField(unique=True, upload_to='Documents/'),
        ),
        migrations.AlterField(
            model_name='uploaddocuments',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='uploadexams',
            name='exam',
            field=models.FileField(unique=True, upload_to='Examination/'),
        ),
        migrations.AlterField(
            model_name='uploadexams',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
