# Generated by Django 2.2.4 on 2020-04-15 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_auto_20200413_2304'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadSlides',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slide_id', models.CharField(max_length=15)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(default='', max_length=100, unique=True)),
                ('teacher', models.CharField(max_length=200)),
                ('slides', models.FileField(upload_to='Slides/New folder')),
            ],
        ),
    ]
